ALTER TABLE LAST CONVERT TO character SET utf8;
ALTER TABLE INSTA_PROFILE CONVERT TO character SET utf8;

ALTER TABLE POST CONVERT TO character SET utf8;
ALTER TABLE REPLY CONVERT TO character SET utf8;

ALTER DATABASE SocialAnalysis CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE POST CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE POST modify content text charset utf8mb4;

ALTER TABLE POST ADD CONSTRAINT inner_id_FK5 FOREIGN KEY(inner_id) REFERENCES INSTA_PROFILE(inner_id)

ALTER TABLE REPLY CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE REPLY modify reply text charset utf8mb4;

ALTER TABLE INSTA_PROFILE CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE INSTA_PROFILE modify profile text charset utf8mb4;

ALTER TABLE REPLY_4 CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE REPLY_4 modify reply text charset utf8mb4;